CREATE INDEX condition_browse_mesh_term_idx ON condition_browse(mesh_term);
CREATE INDEX intervention_browse_mesh_term_idx ON intervention_browse(mesh_term);
CREATE INDEX mesh_thesaurus_mesh_term_idx ON mesh_thesaurus(mesh_term);