SELECT DISTINCT MESH_TERM from condition_browse
WHERE MESH_TERM like "%HIV%";

select distinct MESH_TERM from condition_browse limit 1000;

# Select HIV from conditions but exclude words that contain HIV like shivering
SELECT DISTINCT CONDITION_NAME FROM conditions
WHERE CONDITION_NAME REGEXP "HIV"
AND NOT CONDITION_NAME REGEXP "[[:alpha:]]{1}HIV|HIV[[:alpha:]]{1}";

SELECT NCT_ID FROM conditions
WHERE CONDITION_NAME REGEXP "HIV"
AND NOT CONDITION_NAME REGEXP "[[:alpha:]]{1}HIV|HIV[[:alpha:]]{1}";


SELECT 
	ORG_STUDY_ID, 
	SOURCE, 
	BRIEF_TITLE, 
	HAS_DMC,
	BRIEF_SUMMARY,
	DETAILED_DESCRIPTION,
	OVERALL_STATUS,
	START_DATE,
	COMPLETION_DATE,
	COMPLETION_DATE_TYPE,
	PRIMARY_COMPLETION_DATE,
	PRIMARY_COMPLETION_DATE_TYPE,
	PHASE,
	STUDY_TYPE,
	STUDY_DESIGN,
	NUMBER_OF_ARMS,
	NUMBER_OF_GROUPS,
	ENROLLMENT_TYPE,
	ENROLLMENT,
	CRITERIA,
	GENDER,
	MINIMUM_AGE,
	MAXIMUM_AGE,
	HEALTHY_VOLUNTEERS,
	SAMPLING_METHOD,
	STUDY_POP,
	IS_FDA_REGULATED,
	WHY_STOPPED
FROM clinical_study LIMIT 1000;

